package mariam.wishlist.server.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseHandler {

    private Connection connection;

    public void connect(String url, String username, String password) throws SQLException {
        connection = DriverManager.getConnection(url, username, password);
    }

    public void disconnect() throws SQLException {
        connection.close();
    }

    public ResultSet executeQuery(String query) throws SQLException {
        Statement statement = connection.createStatement();
        ResultSet resultSet = statement.executeQuery(query);
        return resultSet;
    }

    public PreparedStatement getPreparedStatement(String query) throws SQLException {
        return getPreparedStatement(query, Statement.NO_GENERATED_KEYS);
    }

    public PreparedStatement getPreparedStatementReturningGeneratedKeys(String query) throws SQLException {
        return getPreparedStatement(query, Statement.RETURN_GENERATED_KEYS);
    }

    private PreparedStatement getPreparedStatement(String query, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(query, autoGeneratedKeys);
    }

}
